MovieShop/MovieShopMVC/Controllers/GenresController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class GenresController : Controller
    {
        private readonly IGenreService _genreService;

        public GenresController(IGenreService genreService)
        {
            _genreService = genreService;
        }
        public async Task<IActionResult> Details(int id)
        {
            // Show List of Genres in the header of LayoutPage Hint: Use PartialView and use Bootstrap dropdown to show genres
            // Use <a> with name of genre and when clicked go to database and show list of movies belong to that genre
            var genreDetails = await _genreService.GetGenreDetails(id);
            return View(genreDetails);
        }
    }
}

MovieShop/MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var movieDetails = await _movieService.GetMovieDetails(id);
            // call the database and get movie details by id
            return View(movieDetails);
        }
    }
}

MovieShop/MovieShopMVC/Controllers/UserController.cs
using ApplicationCore.Entities;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly ICurrentUserService _currentUserService;
        private readonly IUserService _userService;
        public UserController(ICurrentUserService currentUserService, IUserService userService)
        {
            _currentUserService = currentUserService;
            _userService = userService;
        }
        // GET: /<controller>/
        // user/GetAllPurchases
        //[Authorize]
        public async Task<IActionResult> Purchases()
        {
            var userId = _currentUserService.UserId;
            // id from the cookie and send that id to UserService to get all his/her movies.
            // Filters **Important interview question** 
            var movieCards = await _userService.GetPurchasedMovies(userId);
            return View(movieCards);
        }

        //[Authorize]
        public async Task<IActionResult> Favorites()
        {
            var userId = _currentUserService.UserId;
            var movieCards = await _userService.GetAllFavorites(userId);
            return View(movieCards);
        }

        //[Authorize]
        public async Task<IActionResult> Profile()
        {
            var userId = _currentUserService.UserId;
            // id from the cookie and send that id to UserService to get all his/her movies.
            // Filters **Important interview question** 
            var userProfile = await _userService.GetUserInfo(userId);
            return View(userProfile);
        }

        //[Authorize]
        public Task<IActionResult> EditProfile()
        {
            throw new NotImplementedException();
        }

        //[Authorize]
        public Task<IActionResult> BuyMovie()
        {
            throw new NotImplementedException();
        }

        //[Authorize]
        //public async Task<IActionResult> FavoriteMovie()
        //{
        //    return View();
        //}
    }
}

MovieShop/MovieShopMVC/Views/Shared/_Layout.cshtml
@inject ApplicationCore.ServiceInterfaces.IGenreService _genreService
@inject ApplicationCore.ServiceInterfaces.ICurrentUserService _currentUser
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #e3f2fd;">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Movie Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @{
                            var userId = _currentUser.UserId;
                            if (_currentUser.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <span class="nav-link text-primary font-weight-bold"> Welcome back, @_currentUser.FullName! </span>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <a typ="button" class="btn btn-outline-primary rounded-pill" asp-controller="Account" asp-action="Login">
                                        Login
                                    </a>
                                </li>
                            }
                        }
                    </ul>
                </div>
                <div class="dropdown bg-light">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Genres
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        @foreach (var genre in await _genreService.GetAllGenres())
                        {
                            <a class="dropdown-item" asp-controller="Genres" asp-action="Details" asp-route-id="@genre.Id">@genre.Name</a>
                        }
                    </div>
                </div>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
                <div class="dropdown ml-2">
                    <button class="btn btn-secondary bg-transparent" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bars text-primary"></i>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        @{
                            if (!_currentUser.IsAuthenticated)
                            {
                                <a class="dropdown-item" asp-controller="Account" asp-action="Register">Register</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="Index" asp-route-id="">Home</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="Privacy" asp-route-id="">Privacy</a>
                            }
                            else
                            {
                                <a class="dropdown-item" asp-controller="User" asp-action="Profile" asp-route-id=@userId>User Profile</a>
                                <a class="dropdown-item" asp-controller="User" asp-action="Favorites" asp-route-id=@userId>Favorites</a>
                                <a class="dropdown-item" asp-controller="User" asp-action="Purchases" asp-route-id=@userId>Purchases</a>
                                <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a>
                            }
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid mt-1">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShop/MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieCardResponseModel

<div class="card mb-4">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
    </a>
</div>